const DailyLife_Data=[
    {
        blog_name:"Contradiction of karma and Dharma",
        blog_description:"The factual thing is that what we are asked, suggested, and suppose to do is called dharma, like helping others,",
        blog_content:"The factual thing is that what we are asked, suggested, and suppose to do is called dharma, like helping others, talking politely to all, doing things on time, focusing on one thing at a time and many more is our dharma.<br/><br/> However, what we do or perform is called karma, for instance, I am up for completing a presentation by the next one hour this is my dharma. If my baby is hungry and he wants food, then offering him food before any presentation completion is my karma.<br/><br/>Dharma is nothing but somehow some ridiculous concept fictitious or genuinely happened, which becomes popular and is considered compulsory to be followed bribed along with the theory of reciprocation of good karma. This concept of reciprocation of good rewards for good karma could have some existence in past, we're keeping an eye on every big and small deed by people was easy as there were just a handful of people living in town. Considering karma to be good or bad or even waiting for the results of good or bad karma is no more the go-to thing for the people of the planet now. There are more than 7.7 billion people on the planet, striving and struggling every day in the race of getting a good life and lifestyle for them and their families. Nobody has such patience to wait for good karma to pay them the rewards, what they deserve. <br/><br/>Imagine it this way if I found a beggar with a normal physical appearance on the street begging for money or food. Helping him at this time is my dharma. I gave him money and he ended up buying some cigarettes or some alcohol out of it, or if I offer him a good quantity of flour, he eventually sale it again for some money and buys alcohol and cigarettes for that. Do it this time doing a good karma pay benefit to any of the two persons. Neither the man who gave him money nor that beggar has done anything productive with that money. <br/><br/>In the above case, the dharma says to help but the karma is not supporting the dharma completely as there is no value of it. This is how dharma contradicts to karma.",
        blog_image:"https://thumbs.dreamstime.com/b/hinduism-karma-way-life-word-cloud-sign-98870341.jpg"
    },
    {
        blog_name:"Importance of sleeping positions",
        blog_description:"Sleeping is the most important phenomenon of life. Sleep is something which is not an",
        blog_content:"Sleeping is the most important phenomenon of life. Sleep is something which is not an essential element for improving the physical strength of the body but also a vital element that enhances a relaxed mind state.<br/><br/>The time and position of sleep greatly affect the health of the person. The regular health related matterspeople have been complaining about nowadays like weight-gain, weight loss,weakness, or even insomnia are the results of bad sleeping time and position.<br/><br/>Whatever we do out of certain limits will cause trouble. Same do happens with the natural limits defined for sleep, be it the natural time limit of going to sleep or the limit of waking up.  “Early to bed and early to rise, makes a man healthy, wealthy, and wise”, is something not just a poem but a truly accepted fact for having a healthy life.<br/><br/>Not just the time but you’re sleeping pattern or position also affects your entire physical and mental health like-<br/><br/><b>Sleeping on your back</b>- This position is good for snorers also this position helps a full relaxation to the spine. Back sleeping is better without a pillow.Cosmetic value also enhances, by creating better blood flow to face and decreasing wrinkles and aging of face skin. Back sleeping is bad sometimes as it causessleep apnea.<br/><br/><b>Sleeping on your</b> side- Majority of the people on this planet are found to be comfortable sleeping by their sides. Even doctors recommend sleeping sideways, especially towards the left side, during pregnancy. For heart patients, insomniacs alsocomfort by sleeping toward the left side.<br/><br/> <b>Sleeping on stomach</b> - The only good, counted for stomach sleeper is that it eases snoring up to some extent only. The worst sleeping position is considered to be sleeping on your stomach because it so badly affects the natural shape of your spine. It causes a lot of strain to the neck. It also causes increased wrinkles on face skin.<br/><br/>Above are a few common positions observed in the sleeping pattern of people, as sleeping loses our consciousness up to a great extent, it is just the way you train your body to sleep in not just the comfiest but also the physiologically better position in the course oftime.        ",
        blog_image:"https://c0.wallpaperflare.com/preview/731/1016/856/bedroom-trip-hotel-sleep.jpg"
    }
]
export default DailyLife_Data;